### ISSUE TITLE
Termination condition of `check!()`?

### ISSUE THREAD

**Issue by ckaran** [camshaft/bolero#10]
I've rewritten most of my unit tests to use `check!()` at this point, and have run into an interesting problem; a couple of my tests aren't terminating.  I put in a `print!("{:?}: {:?}: date = {:?}\r", file!(), line!(), std::time::SystemTime::now());` call at the start of the closure for `check!()`, so I know that it is making progress (not a hung process), but it can take several hours before these particular unit tests terminate.  So, how does `check!()` decide to terminate?  Can we limit its runtime, e.g. by passing in a `std::time::Duration`, and have the test time out if it exceeds that value?

**Comment by camshaft** [comment]
You can find the [`RngEngine` implementation here](https://github.com/camshaft/bolero/blob/master/bolero-engine/src/rng.rs#L51). It will iterate until it's tested `iterations` number of times. If `None` is returned, the count is _not_ incremented, so if your generator is really difficult to satisfy it's going to take a long time.

**Comment by ckaran** [comment]
So, until enough 'stuff' has been generated, it won't terminate, correct?  Is there a way to debug what is going on?  That is, I know that everything boils down to some implementation of `TypeGenerator` somewhere, and I'm assuming one (or more) of them is not producing, but I don't know which ones are doing that.

**Comment by camshaft** [comment]
We may need to add an upper bound to the total number of iterations and either print a warning or panic, indicating a hard to satisfy generator.

**Comment by ckaran** [comment]
I think making the behavior user-selectable would be best.  I can think of cases where I'd rather let it run for a long time, and other cases where I'd like it to panic, each of which would need to be chosen on an individual basis.

**Comment by camshaft** [comment]
> I can think of cases where I'd rather let it run for a long time

Churning on invalid input isn't really productive, though. Keep in mind you're not actually running any of your test code until a valid value is returned. Ideally a generator produces a valid input on every iteration. If the majority are invalid it's an indicator that the generator has been misconfigured or there's a bug. I think panicking after something like `iterations * 2` is the best option here.

**Comment by ckaran** [comment]
>  I think panicking after something like iterations * 2 is the best option here.

OK, I can live with that.  Combined with improved documentation of useful features (like what you mentioned in #9), this would be enough to catch when the `TypeGenerator` implementation has gone a little nuts. 

Actually, that brings up an interesting thought; is it possible to track statistics on a per `TypeGenerator` implementation basis?  As you saw in #9, I was doing a *lot* of filtering in one implementation.  Having a way of determining which implementation is the bad one would make it much easier to fix.
