### ISSUE TITLE
impl TypeGenerator for chrono::DateTime, chrono_tz::Tz, etc?

### ISSUE THREAD

**Issue by Ekleog** [camshaft/bolero#106]
I'm wondering, where do you think TypeGenerator impls for widely-used crates should live? I just tried to add `#[derive(TypeGenerator)]` to a crate of mine that uses `chrono`, and had to fall back to using `arbitrary` after noticing impls of TypeGenerator for chrono types don't seem to exist yet.

Relatedly, do you think a fallback like the following would make sense?
```rust
#[derive(TypeGenerator)]
struct Foo {
    bar: usize,
    #[type_generator(from_arbitrary)]
    baz: BazIsArbitraryButNotTypeGenerator,
}
```

Or maybe it's too much effort to be worth it, and it'd be better to just spend that effort upstreaming bolero-generator everywhere

**Comment by camshaft** [comment]
I think it would be great to have adapters for alternative generator crates, especially if they're widely used like `arbitrary`.

```rust
pub fn gen_arbitrary<T: Arbitrary>() -> ArbitraryGenerator<T> {
    ...
}
```

This would also allow for the feature described in #31.

**Comment by Ekleog** [comment]
Hmm that sounds nice! FWIW I've opened a related https://github.com/chronotope/chrono-tz/pull/124 at chrono, where I ask whether they'd be interested in upstream bolero support; I'm also trying to look into writing such a generator.

Just, I'm not sure I understand, why are you suggesting returning an `ArbitraryGenerator: ValueGenerator` and not a `ArbitraryGenerator: TypeGenerator`?

My understanding had been that upstream should always derive TypeGenerator, and downstream can then parameterize it by adding bounds to it using ValueGenerator / TypeValueGenerator, but TBH I'm not entirely sure I understand this part of the API.

**Comment by Ekleog** [comment]
Turns out actually trying to implement the PR gave me the answer about the difference between TypeGenerator and ValueGenerator; I've submitted #108 with the code that I'm using in my current project.
