### ISSUE TITLE
gen-arbitrary is slow

### ISSUE THREAD

**Issue by Ekleog** [camshaft/bolero#111]
Hey! So I recently tried deriving TypeGenerator with [a reasonably small type](https://github.com/Ekleog/risuto/blob/main/risuto-server/src/fuzz.rs#L162-L167).

Basically, this was like using `bolero::check!().with_type::<Vec<(#[gen_arbitrary()] Uuid, String, String)>>()`.

Turns out just doing this led to the test taking more time than I would wait just to _generate the first input_ (I bisected with a `panic!()` and ended up at the top of the check, because I was convinced I had a deadlock somewhere). `perf` confirms, almost all the time was being spent in generating `String`s.

Sure this was using `cargo test`, so without optimizations on. But still, maybe it'd make sense to have the default `TypeGenerator` for basic types be somewhat limited in size, so they don't literally take minutes to generate with relatively simple types? (I must say I have not tried actually profiling when fuzzing yet, so I don't know how  badly this affects fuzzers yet, but for tests not using `gen_with` basically made the generated code impossible-to-use)

**Comment by camshaft** [comment]
Hmm that's surprising the `String` is taking so long. It should only generate values up to 64 bytes in length:

https://github.com/camshaft/bolero/blob/62ae9dd0d28ce707237f3812d35166b8bea2f75b/bolero-generator/src/alloc/mod.rs#L17

There may be a bug in the string generator that causes this behavior. But in generate we try to have reasonable defaults of limits for collections.

**Comment by Ekleog** [comment]
Hmmmmm ok so it looks like… `Vec<(String, String, String)>` runs in 1s, but `Vec<(UserId, String, String)>` takes 31s, where `UserId` is just `#[gen_arbitrary()] Uuid`. So this is probably just slowness of `gen_arbitrary()`. I have literally no idea why `perf` reported me all the samples inside string-generation.

Anyway, this seems to be… due to the fact… that `uuid`'s `Arbitrary` implementation [does not actually report proper bounds](https://docs.rs/uuid/1.2.2/src/uuid/external/arbitrary_support.rs.html#5-14), which in turn lead it to hit `ABUSIVE_SIZE` from the gen-arbitrary PR, and generating this many random bytes was slow.

So I'm submitting a PR to `uuid` to have the proper size hint, and also changing the gen-arbitrary PR so that ABUSIVE_SIZE is much lower but direct-mode drivers ignore it. This means that DirectRng could start taking a basically infinite amount of time for generating `arbitrary` types that do not report proper bounds, but… TBH I think it makes sense? And I don't see why anyone would ever use `DirectRng` anyway

**Comment by Ekleog** [comment]
The uuid fix is at https://github.com/uuid-rs/uuid/pull/657 . I also (rebased and) pushed a new commit to `gen_arbitrary`, that reduces the slowness in case of misbehaved `arbitrary` implementation :)

**Comment by adpaco-aws** [comment]
Hi @Ekleog , do you think this issue can be closed now?
