### ISSUE TITLE
Trophy case?

### ISSUE THREAD

**Issue by Ekleog** [camshaft/bolero#113]
Hey!

I just incidentally found a panic inside chrono, while fuzzing my web server: https://github.com/chronotope/chrono/pull/941

So I'm wondering if you'd want to introduce a trophy case to cargo-bolero, similar to the one cargo-fuzz has? :)

**Comment by Ekleog** [comment]
(sorry for misclicking and creating the issue without any contents, this is now fixed)

**Comment by Ekleog** [comment]
And a follow-up commit to my own code, which even after the chrono fix was still panicking on certain remote user input (so it was a DoS): 9c23cc863d7d346e8a5e61e98eb99431cf39896f

**Comment by camshaft** [comment]
I think I would prefer adding to https://github.com/rust-fuzz/trophy-case and just specifying the engine used and bolero. Something like:

```
libfuzzer + [bolero](https://camshaft.github.io/bolero/)
```

**Comment by camshaft** [comment]
Nice find, BTW!

**Comment by Ekleog** [comment]
Sounds good to me! I'll submit there. Just so I don't forget about it, another one in my code this time, though related to lack of a proper API from chrono: https://github.com/chronotope/chrono/issues/948 / the panic DoS fix at https://github.com/Ekleog/risuto/commit/1a439709abd02b2e83c65a0b4688b591420c534c (turns out Havana has timezone shifts that make midnight an invalid time on some dates)

**Comment by Ekleog** [comment]
Ok, I've opened https://github.com/rust-fuzz/trophy-case/pull/121 ; and can now close this :)
