### ISSUE TITLE
Can you run multiple tests in parallel?

### ISSUE THREAD

**Issue by ckaran** [camshaft/bolero#21]
I'm using [GNU parallel](https://www.gnu.org/software/parallel/) to parallelize all testing under bolero; I basically used `cargo bolero list > all_tests`, and then then hacked the result to look similar to the following:

```bash
cargo bolero fuzz --time 60sec activities::node_activities::error::tests::clone
cargo bolero fuzz --time 60sec activities::node_activities::error::tests::debug
cargo bolero fuzz --time 60sec activities::node_activities::error::tests::partial_eq
cargo bolero fuzz --time 60sec activities::node_activities::error::tests::partial_ord
cargo bolero fuzz --time 60sec activities::node_activities::error::tests::serialize
...
```

I then run everything using

```bash
cat all_tests | parallel --progress --eta --nice 10
```

which seems to work, but it occurred to me that bolero might not be able to correctly handle being run on the same project concurrently.  So, is it safe to do this?  What about if I remove the `target` directory in between, forcing bolero to rebuild when the command is run?

**Comment by camshaft** [comment]
I can't think of anything in bolero that would get in the way of you doing that.

**Comment by ckaran** [comment]
> I can't think of anything in bolero that would get in the way of you doing that. 

Good to know!  By the way, if you ever put in a 'tips & tricks' section into the documentation, the one above could be useful, especially if you happen to have a large multicore server.

> But I wouldn't remove the target directory as that contains all of the compiled fuzz targets.

I agree, but `cargo clean` already removes it, and since that's how I verify that I'm not triggering something weird (like #18), I have to keep on doing it...
