### ISSUE TITLE
Integration with arbitrary is broken on bolero 0.11.x

### ISSUE THREAD

**Issue by glebpom** [camshaft/bolero#237]
On bolero 0.11:

This test:
```
        bolero::check!()
            .with_arbitrary::<String>()
            .cloned()
            .for_each(|input| {
                println!("{:?}", input);
                true
            });
```

gives only empty strings, but if changing `with_arbitrary` to `with_type`, it gives random strings.

**Comment by camshaft** [comment]
Thanks for opening an issue! I've got a fix in #238, along with new test assertions making sure it doesn't happen again.
