### ISSUE TITLE
Generating larger sets of operations for structured testing

### ISSUE THREAD

**Issue by mkforsb** [camshaft/bolero#244]
While experimenting with the recipe for [structured testing](https://camshaft.github.io/bolero/features/structured-testing.html) I noticed that the generated `Vec<Operation>` never exceeds 64 elements in size. After some digging I believe the reason is [`DEFAULT_LEN_RANGE`](https://github.com/camshaft/bolero/blob/master/lib/bolero-generator/src/alloc/mod.rs#L17) which is used to generate `VecGenerator` via the `impl_values_collection_generator!` macro.

Is there a simple way to increase this limit while staying within the `#[derive(TypeGenerator)]` ... `check!().with_type...for_each` workflow?

The most clean workaround I've come up with so far is the following device (which I've only very lightly tested):

```rust
struct RangedVec<T, const LO: usize, const HI: usize>(pub Vec<T>) where T: 'static + TypeGenerator;

impl<T, const LO: usize, const HI: usize> TypeGenerator for RangedVec<T, LO, HI> where T: 'static + TypeGenerator {
    fn generate<D: Driver>(driver: &mut D) -> Option<Self> {
        let len = driver.gen_usize(Bound::Included(&LO), Bound::Included(&HI))?;
        Some(RangedVec((0..len).map(|_| T::generate(driver)).collect::<Option<_>>()?))
    }
}
```

This allows for e.g:
```rust
check!()
    .with_type::<RangedVec<Operation, 0, 1024>>()
    .for_each(|operations| { ... })
```

Is there something simpler already available in bolero that I'm missing?

**Comment by camshaft** [comment]
Hey thanks for the question. The way to accomplish is with the `with_generator` function:

```rust
check!()
    .with_generator(gen::<Vec<Op>>().with().len(0..=1024))
    .for_each(|ops| { ... })
```

The documentation could probably use an example of this
