### ISSUE TITLE
Shrinker runs once when `shrink_time` is zero.

### ISSUE THREAD

**Issue by mkforsb** [camshaft/bolero#248]
I tried setting `.with_shrink_time(ZERO)` to fully disable input shrinking for a proptest, but noticed that the shrinker only checks if the shrinking time is exhausted after running its first iteration: [shrink.rs#L100-L103](https://github.com/camshaft/bolero/blob/master/lib/bolero-engine/src/shrink.rs#L100-L103). In my case this causes a rather large delay whenever there is a test failure, which is annoying during test development.

Is there some other feature besides adjusting the shrinking time for fully disabling shrinking?

If not, do you think [this approach](https://github.com/mkforsb/bolero/commit/996274a7ac116c2676dcf82beb11d56997022ff1) could be viable for a PR?

**Comment by camshaft** [comment]
Yeah setting it to zero should disable shrinking so if it doesn't then it's a bug. I think what you have looks like a reasonable fix.
