### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by Ekleog** [camshaft/bolero#85]
Right now the latest (0.7.0) release of bolero depends on libtest-mimic 0.3, which depends on crossbeam-channel 0.4, which has a security vulnerability.

It's certainly not a big deal as bolero is only used for tests anyway, but in order to not have automated tools unhappy, would it be possible to make a new release, given current master already depends on libtest-mimic 0.4, which depends on crossbeam-channel 0.5, thus fixing the issue?

Anyway, thank you for bolero once again!

EDIT: BTW, I also noticed there's no tag for cargo-bolero-0.7.0, which makes it harder for packagers to update the distro packages that provide it. I'm maintaining the nixos one, would it be possible for you to take advantage of this and add a tag on the commit on which cargo-bolero-0.7.0 was released? :)

**Comment by camshaft** [comment]
I guess I published a release without tagging or pushing... not sure how that happened. I'll do another release once the current round of fixes goes through.

**Comment by Ekleog** [comment]
Awesome, thanks!
