### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by zhassan-aws** [camshaft/bolero#87]
I'm unable to build bolero from source:
```
$ git clone git@github.com:camshaft/bolero.git
Cloning into 'bolero'...
remote: Enumerating objects: 2526, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 2526 (delta 158), reused 168 (delta 139), pack-reused 2289
Receiving objects: 100% (2526/2526), 2.06 MiB | 12.46 MiB/s, done.
Resolving deltas: 100% (1385/1385), done.
$ cd bolero/
$ cargo build
    Updating crates.io index
error: package `os_str_bytes v6.2.0` cannot be built because it requires rustc 1.57.0 or newer, while the currently active rustc version is 1.56.1
```
The `os_str_bytes` crate is an indirect dependency of `libtest-mimic`:
```
$ cargo tree -i os_str_bytes
os_str_bytes v6.2.0
└── clap_lex v0.2.4
    └── clap v3.2.16
        └── libtest-mimic v0.4.1
            └── bolero v0.6.2 (/home/ubuntu/git/tmptmp/bolero/bolero)
                [dev-dependencies]
                └── cargo-bolero v0.6.2 (/home/ubuntu/git/tmptmp/bolero/cargo-bolero)
```
which was bumped to version 0.4.1 recently via https://github.com/camshaft/bolero/commit/5578547c5efb8c0902f0a560cc41511c2c9176a7.

OS version: Ubuntu 20.04

**Comment by zhassan-aws** [comment]
Updating the version in `rust-toolchain` to 1.57.0 fixes the issue. Should I open a PR for that?

**Comment by camshaft** [comment]
Well that's unfortunate... Looks like it was just for the static assert ability: https://github.com/dylni/os_str_bytes/commit/c595a420af80c61b4e6d74598e400d3c4bdd8d6a

It should be ok to bump the MSRV to 1.57, though, since it's at least 6 months out, which is s2n-quic's policy.
