### ISSUE TITLE
Possible bug in check!()

### ISSUE THREAD

**Issue by ckaran** [camshaft/bolero#9]
I'm using `check!()` in my unit tests, which calls out to an implementation of `TypeGenerator`.  The implementation is below (I've tried to remove as much stuff as possible for clarity, so the code won't compile as it is).  If you read through the implementation for `TypeGenerator`, you'll see that it is generating a semver 2.0 compliant value, which is then stuffed into a `semver::Version` instance.  The problem is the loop in `gen_alpha_numeric_ascii_character()`; it assumes that either the driver will return `None`, which will then get propagated all the way back up, or it will receive a new, **randomly generated** value.  Given enough time, that would guarantee that the loop would exit.  However, in testing I've discovered that the generator will eventually start returning `0` rather than run out of values.  That means I get stuck in here.  I've done a temporary workaround where I instead of the loop, I use an ordinary `for` loop and loop 100 times, returning `None` if I reach the end of the loop.  But this isn't quite what I'd expect out of this.

```rust
use semver::Version;

pub struct Meta {
    /// [SemVer 2.0](https://semver.org/spec/v2.0.0.html) compliant value.
    pub version: Version,
}

impl TypeGenerator for Meta {
    fn generate<R>(driver: &mut R) -> Option<Self>
    where
        R: Driver,
    {
        fn gen_alpha_numeric_ascii_character<R>(driver: &mut R) -> Option<char>
        where
            R: Driver,
        {
            let mut value: u8 = driver.gen()?;
            loop {
                if (value >= 0x41 && value <= 0x5A)
                    || (value >= 0x61 && value <= 0x7A)
                    || (value >= 0x30 && value <= 0x39)
                {
                    break;
                } else {
                    value = driver.gen()?;
                }
            }

            Some(char::from(value))
        }

        fn gen_alpha_numeric_string<R>(driver: &mut R) -> Option<String>
        where
            R: Driver,
        {
            let len: usize = driver.gen()?;

            // This is an arbitrary limit to the number of characters.  If this
            // is too small, increase it as needed.
            let len = len % 20;

            let mut output: String = String::new();
            for _ in 0..len {
                let value = gen_alpha_numeric_ascii_character(driver)?;
                output.push(value);
            }

            Some(output)
        }

        fn gen_identifier<R>(driver: &mut R) -> Option<Identifier>
        where
            R: Driver,
        {
            if driver.gen()? {
                Some(Identifier::Numeric(driver.gen()?))
            } else {
                let num: usize = driver.gen()?;
                let num = num % 5;
                let mut parts: Vec<String> = Vec::new();
                for _ in 0..num {
                    let alpha_num_string = gen_alpha_numeric_string(driver)?;
                    parts.push(alpha_num_string);
                }
                let output: String = join(&parts, ".");

                Some(Identifier::AlphaNumeric(output))
            }
        }

        fn gen_vec_of_identifiers<R>(driver: &mut R) -> Option<Vec<Identifier>>
        where
            R: Driver,
        {
            let num: usize = driver.gen()?;
            let num = num % 5;
            let mut output: Vec<Identifier> = Vec::new();
            for _ in 0..num {
                let identifier = gen_identifier(driver)?;
                output.push(identifier);
            }

            Some(output)
        }

        let major: u64 = driver.gen()?;
        let minor: u64 = driver.gen()?;
        let patch: u64 = driver.gen()?;
        let pre: Vec<Identifier> = gen_vec_of_identifiers(driver)?;
        let build: Vec<Identifier> = gen_vec_of_identifiers(driver)?;

        let version: Version = Version {
            major,
            minor,
            patch,
            pre,
            build,
        };

        Some(Meta {
            version,
        })
    }
}
```

**Comment by camshaft** [comment]
If you look at the [`TypeGenerator` implementation for `char`](https://github.com/camshaft/bolero/blob/master/bolero-generator/src/char.rs) it coerces the random value into a valid value. I would recommend against calling `gen` until you get a valid value because, as you've found out, can take a long time to satisfy (or possibly never).

**Comment by ckaran** [comment]
I thought that `driver.gen()?` would ensure that I'm getting valid values only.  Am I misunderstanding how the drivers work?

**Comment by camshaft** [comment]
It'll return a valid value for that type. The problem is in `gen_alpha_numeric_ascii_character` where you're constraining the value further and continually calling `gen` until it returns a value within those bounds. The better approach would be to round to the nearest value within your constraints. Alternatively, you could use a set of ranges and [`one_of`](https://docs.rs/bolero/0.4.2/bolero/generator/trait.OneOfExt.html#tymethod.one_of):

```rust
let gen_char = [0x41..0x5A, 0x61..0x7A, 0x30..0x39].one_of();
let value = gen_char.generate(driver)?;
Some(char::from(value))
```

**Comment by ckaran** [comment]
I had no idea that `[0x41u8..0x5A, 0x61..0x7A, 0x30..0x39].one_of();` was even an option! :open_mouth:!

That said, it didn't fix the bug... I can see that it is now correctly outputting values in the given ranges, but the tests don't terminate.

**Comment by ckaran** [comment]
OK, I had time to run this until it crashed.  I ran with `cargo test --release -j1 -- --ignored` to ensure that threading wasn't causing any issues, but I eventually had a crash with the following error:

```
memory allocation of 12062401509 bytes failed
```

I'm guessing that the issue is from the implementation of `TypeGenerator` on my own `Scenario` type:

```rust
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, TypeGenerator)]
pub struct Scenario {
    pub description: String,
    pub scenario_id: ScenarioId,
    pub output_file: String,
    pub channels:    Vec<ChannelInfo>,
    pub clients:     Vec<ClientInfo>,
    pub messages:    Vec<Message>,
}
```

`ScenarioId` is just a newtype around a `u64`, so it's tiny, but the strings and vectors can be potentially very large.  In addition, the types that are being used within the vectors can be very large (potentially unbounded in size).  Is there a way of bounding the sizes of generated collections (`Vec` and `VecDeque` in particular)?  That should solve this problem.

**Comment by camshaft** [comment]
> I had no idea that [0x41u8..0x5A, 0x61..0x7A, 0x30..0x39].one_of(); was even an option!

The documentation needs to be improved; still working on it.

>  Is there a way of bounding the sizes of generated collections (Vec and VecDeque in particular)?

Yep. There's a `generator` attribute available for each of the fields:

```rust
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, TypeGenerator)]
pub struct Scenario {
    #[generator(String::gen().with().len(0usize..5))]
    pub description: String,

    pub scenario_id: ScenarioId,

    #[generator(String::gen().with().len(5usize..10))]
    pub output_file: String,

    #[generator(Vec::gen().with().len(0usize..10))]
    pub channels:    Vec<ChannelInfo>,

    #[generator(Vec::gen().with().len(1usize..5))]
    pub clients:     Vec<ClientInfo>,

    #[generator(Vec::gen().with().len(1usize..5))]
    pub messages:    Vec<Message>,
}
```

**Comment by ckaran** [comment]
I made the changes you suggested just before lunch; the tests have now been running for about an hour, with one of them failing so far.  However, no memory crashes yet.  I'll leave it running until I leave for the day, with any luck I'll have something to report before I leave for the weekend.

**Comment by ckaran** [comment]
OK, the tests have been running for about 3.5 hours now, with no sign of terminating.  I'll see what I can figure out next week.
