### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedVersionFormat'

### ISSUE THREAD

**Issue by wizeman** [camshaft/bolero#97]
While trying to run bolero following the instructions from the `README.md`, I ran into this error:

```bash
$ cargo bolero test fuzz_add
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedVersionFormat', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-bolero-0.8.0/src/project.rs:167:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ env RUST_BACKTRACE=1 cargo bolero test fuzz_add
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedVersionFormat', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-bolero-0.8.0/src/project.rs:167:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: cargo_bolero::project::Project::rustflags
   4: cargo_bolero::project::Project::cmd
   5: cargo_bolero::selection::Selection::test_target
   6: cargo_bolero::libfuzzer::test
   7: cargo_bolero::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Any ideas?

**Comment by camshaft** [comment]
Hmm looks like the `rustc_version` isn't able to parse the version

https://github.com/camshaft/bolero/blob/88834fbf32c371da710fb202b4f4bcce178b29fb/cargo-bolero/src/project.rs#L157-L167

Can you run the same command and share the output?

**Comment by wizeman** [comment]
> Can you run the same command and share the output?

Well, I don't know what value `toolchain` has in that code, but since I only have one toolchain then I assume it's that one.

Here's the output:

```bash
$ rustup run stable-x86_64-unknown-linux-gnu rustc -vV
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by camshaft** [comment]
Oh that might be the problem, then. Is it fixed if you install `nightly`? By default, the libfuzzer engine uses nightly to enable sanitizer features.

If that fixes it, we'll need to either install nightly automatically or error out and indicate that it needs to be installed given the configuration.

**Comment by wizeman** [comment]
Yes, that seems to have fixed the issue. Thanks!

**Comment by Ekleog-NEAR** [comment]
With #82 recently merged, I think this should now be fixed? (or, to be precise, at least will show a proper error message in the 0.9 cargo-bolero release)
